### ISSUE TITLE
Use min_value for minimum range in code generator

### ISSUE THREAD

**Issue by qur786** [manufac-analytics/reactjs-calendar-heatmap#12]
- create a new issue in our repo, revert the change
- create a new issue in the original repo, ask the creator

_Originally posted by @maneetgoyal in https://github.com/manufac-analytics/reactjs-calendar-heatmap/pull/7#discussion_r861473329_

**Comment by qur786** [comment]
The issue created in the official repo :
https://github.com/g1eb/reactjs-calendar-heatmap/issues/32

**Comment by qur786** [comment]
@maneetgoyal sir ,  this issue has been answered by the author https://github.com/g1eb/reactjs-calendar-heatmap/issues/32#issuecomment-1113507274

**Comment by maneetgoyal** [comment]
min can be used

**Comment by qur786** [comment]
> min can be used

for very low value, the visual elements would be white, so it won't appear properly in the white background. Should we change the `color range between grey and the value provide by the user` for linearScale so that it doesn't gets completely white when the value is extremely low

**Comment by qur786** [comment]
> > min can be used
> 
> for very low value, the visual elements would be white, so it won't appear properly in the white background. Should we change the `color range between grey and the value provide by the user` for linearScale so that it doesn't gets completely white when the value is extremely low

As you can see for the year 2012 it is completely white and it is not visible with white backfground.
![Screenshot from 2022-04-30 11-51-14](https://user-images.githubusercontent.com/79472606/166094407-5957457b-d7e8-46f4-b24f-05ce5336ed9d.png)

**Comment by maneetgoyal** [comment]
>Should we change the color range between grey and

~can be done via a new PR~, actually lets skip it for now

**Comment by maneetgoyal** [comment]
cc @qur786 updated the comment
