### ISSUE TITLE
Use Intl.PluralRules

### ISSUE THREAD

**Issue by qur786** [manufac-analytics/reactjs-calendar-heatmap#25]
it is okay for now, but make a new issue and look into https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/PluralRules/PluralRules

_Originally posted by @maneetgoyal in https://github.com/manufac-analytics/reactjs-calendar-heatmap/pull/23#discussion_r862336288_

**Comment by qur786** [comment]
@maneetgoyal Since we are copying heatmaps from d3 , do we need it any more?

**Comment by maneetgoyal** [comment]
Closing
