### ISSUE TITLE
framework: '@storybook/react',

### ISSUE THREAD

**Issue by maneetgoyal** [manufac-analytics/reactjs-calendar-heatmap#8]
See if this should be added to d3 portfolio and app repo also, I think we aren't using it there but still things are working, try to research on this property helps and add it to the repos also if needed

_Originally posted by @maneetgoyal in https://github.com/manufac-analytics/reactjs-calendar-heatmap/pull/5#discussion_r860473520_

**Comment by qur786** [comment]
@maneetgoyal sir, couldn't find much about @storybook/react other than the npm registry of this package https://www.npmjs.com/package/@storybook/react .

**Comment by qur786** [comment]
@maneetgoyal sir other than the `@storybook/react` package itself we don;t have much information regarding the use case of `framework` key in the main.js . In the docs, they don't have much explaination as well.

**Comment by qur786** [comment]
https://github.com/storybookjs/storybook/discussions/18102#discussioncomment-2667923 Official explaination of having `framework` field in main.js by storybook team.
We need to include it in the App and D3 portfolio repos @maneetgoyal as well sir.
